#pragma once
#define SCREEN_WIDTH 150
#define SCREEN_HEIGHT 150

# define TILE_WIDTH 3
# define TILE_HEIGHT 3

#define LEVEL_WIDTH 50 //(SCREEN_WIDTH / TILE_WIDTH)
#define LEVEL_HEIGHT 50 // (SCREEN_HEIGHT / TILE_HEIGHT)